import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Profile.module.css'

// bootstrap
import 'bootstrap/dist/css/bootstrap.min.css';

import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

// tab
import Tab from 'react-bootstrap/Tab';
import Tabs from 'react-bootstrap/Tabs';
import Nav from 'react-bootstrap/Nav';

// form
import Form from 'react-bootstrap/Form';


export default function Chat() {

   
    return (
        

        <div className={styles.chat_container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <Container>
                <Row>
                    <Col md={3} sm={12} lg={3}>
                        <div className={styles.chat}>
                            <div className={styles.chat_box}>
                                <Row>
                                    <Col md={4} sm={4} xs={4}>
                                        <div className={styles.chat_img}>
                                            <img src="/logo.jpg" />
                                        </div>
                                    </Col>
                                    <Col md={8} sm={8} xs={8}>
                                        <div className={styles.chat_name}>
                                            <h3>Sushma</h3>
                                            <p>Get access to exclusive information and interect with fellow auto lovers.</p>
                                            <h4><img src="/logo.jpg" /> <span> Newbie</span></h4>
                                            <div className={styles.edit}>
                                                <p>Joined in Jul 2022</p>
                                                <p><a href="#">Edit</a></p>
                                            </div>
                                        </div>
                                    </Col>
                                </Row>
                            </div>
                            <div className={styles.chat_box2}>
                                <div className={styles.add}>
                                    <p><span>My Garage</span></p>
                                    <p><a href="#">Add/Edit</a></p>
                                </div>
                                <p className={styles.maruti}><span>&#9679;</span> Maruti Suzuki Swift 2014-2021</p>
                                <Row>
                                    <Col md={3} sm={3} xs={3}>
                                        <div className={styles.chat_img2}>
                                            <img src="/icon.jpg" />
                                        </div>
                                    </Col>
                                    <Col md={8} sm={8} xs={8}>
                                        <div className={styles.chat_name}>
                                            <p>Help fellow auto lovers by review and answering questions & become a Zigwheels Legend</p>
                                        </div>
                                    </Col>
                                </Row>
                            </div>
                        </div>
                    </Col>
                    <Col md={9} sm={12} lg={9}>
                        <div className={styles.chat2}>
                            <h1>My Activity</h1>
                            <Tab.Container id="left-tabs-example" defaultActiveKey="first">
                                <Nav variant="pills" className={styles.tab_nav}>
                                    <Nav.Item className={styles.tab_item}>
                                        <Nav.Link className={styles.tab_link} eventKey="first">25+<br/><span>Questions For You</span></Nav.Link>
                                    </Nav.Item>
                                    <Nav.Item className={styles.tab_item}>
                                        <Nav.Link className={styles.tab_link} eventKey="second">3<br/><span>Answers</span></Nav.Link>
                                    </Nav.Item>
                                    <Nav.Item className={styles.tab_item}>
                                        <Nav.Link className={styles.tab_link} eventKey="third">0<br/><span>Questions Asked</span></Nav.Link>
                                    </Nav.Item>
                                    <Nav.Item className={styles.tab_item}>
                                        <Nav.Link className={styles.tab_link} eventKey="four"> 1<br/><span>Questions Followed</span></Nav.Link>
                                    </Nav.Item>
                                    <Nav.Item className={styles.tab_item}>
                                        <Nav.Link className={styles.tab_link} eventKey="five">0<br/><span>Your Reviews</span></Nav.Link>
                                    </Nav.Item>
                                    <Nav.Item className={styles.tab_item}>
                                        <Nav.Link className={styles.tab_link} eventKey="six">0<br/><span>Shortlist</span></Nav.Link>
                                    </Nav.Item>
                                </Nav>
                                <Tab.Content className={styles.tab_content}>
                                    <Tab.Pane className={styles.tab_pane} eventKey="first">
                                        <div className={styles.tab_box}>
                                            <div className={styles.cancle}>
                                                <p><span>Lovkush </span> asked about  Maruti Suzuki Swift 2014-2021</p>
                                                <p className={styles.cancle_btn} >&#x2715;</p>
                                            </div>
                                            <h3>Q. This car CNG variant or not - Swift ?</h3>
                                            <Form className={styles.form}>
                                                <Form.Group className={styles.form_boxes} controlId="formBasicEmail">
                                                    <Form.Control className={styles.form_box} type="text" placeholder="Add your answer" />
                                                </Form.Group> 
                                            </Form>
                                            <h5>View 4 More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>
                                        </div>
                                        <div className={styles.tab_box}>
                                            <div className={styles.cancle}>
                                                <p><span>Lovkush </span> asked about  Maruti Suzuki Swift 2014-2021</p>
                                                <p className={styles.cancle_btn}>&#x2715;</p>
                                            </div>
                                            <h3>Q. This car CNG variant or not - Swift ?</h3>
                                            <Form className={styles.form}>
                                                <Form.Group className={styles.form_boxes} controlId="formBasicEmail">
                                                    <Form.Control className={styles.form_box} type="text" placeholder="Add your answer" />
                                                </Form.Group> 
                                            </Form>
                                            <h5>View 4 More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>

                                        </div>
                                        <div className={styles.tab_box}>
                                            <div className={styles.cancle}>
                                                <p><span>Lovkush </span> asked about  Maruti Suzuki Swift 2014-2021</p>
                                                <p className={styles.cancle_btn}>&#x2715;</p>
                                            </div>
                                            <h3>Q. This car CNG variant or not - Swift ?</h3>
                                            <Form className={styles.form}>
                                                <Form.Group className={styles.form_boxes} controlId="formBasicEmail">
                                                    <Form.Control className={styles.form_box} type="text" placeholder="Add your answer" />
                                                </Form.Group> 
                                            </Form>
                                            <h5>View 4 More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>

                                        </div>
                                        <div className={styles.tab_box}>
                                            <div className={styles.cancle}>
                                                <p><span>Lovkush </span> asked about  Maruti Suzuki Swift 2014-2021</p>
                                                <p className={styles.cancle_btn}>&#x2715;</p>
                                            </div>
                                            <h3>Q. This car CNG variant or not - Swift ?</h3>
                                            <Form className={styles.form}>
                                                <Form.Group className={styles.form_boxes} controlId="formBasicEmail">
                                                    <Form.Control className={styles.form_box} type="text" placeholder="Add your answer" />
                                                </Form.Group> 
                                            </Form>
                                            <h5>View 4 More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>

                                        </div>
                                    </Tab.Pane>
                                    <Tab.Pane className={styles.tab_box} eventKey="second">
                                    <div className={styles.tab_box}>
                                            <div className={styles.cancle}>
                                    <p><span> Prabhat </span> asked about Royal enfield classic 350 (2014-2021) </p>
                                        
                                        </div>
                                         <h3>Q. what is the minimum height of a person reruired to drive a classic 350? </h3>
                                        
                                         <p className={styles.unfollow}> <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16">
  <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
</svg>
                                            Follow Questions <span>|</span> <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chat-left-text-fill" viewBox="0 0 16 16">
  <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/>
</svg>
                                            Add Answers </p>
                                            


                                    </div>
                                   
                                    </Tab.Pane>
                                    <Tab.Pane className={styles.tab_pane} eventKey="third">
                                        <h1>hello</h1>
                                    </Tab.Pane>
                                    <Tab.Pane className={styles.tab_pane} eventKey="four">
                                    <div className={styles.tab_box}>
                                            <div className={styles.cancle}>
                                    <p><span> Plabon </span> asked about hyundai Venue 2019-2022 </p>
                                        
                                        </div>
                                         <h3>Q. Should i go to Hyundai Venue S 1.2L varient or ford freestyle Titanium, as both comes in near about similar price  range? Will I miss out too much in the venue s varient? </h3>
                                        
                                         <p className={styles.unfollow}> <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16">
  <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
</svg>
                                            Unfollow Questions <span>|</span> <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chat-left-text-fill" viewBox="0 0 16 16">
  <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/>
</svg>
                                            Add Answers</p>


                                         <Form.Control className={styles.form_box} type="text" placeholder="Add your answer" />
                                    </div>
                                    </Tab.Pane>
                                    <Tab.Pane className={styles.tab_pane} eventKey="five">
                                        <h1>Ram5</h1>
                                    </Tab.Pane>
                                    <Tab.Pane className={styles.tab_pane} eventKey="six">
                                        <h1>Ram6</h1>
                                    </Tab.Pane>
                                </Tab.Content>
                            </Tab.Container>
                        </div>
                    </Col>
                </Row>
            </Container>


        </div>
        

    )

}